export const halloweenPrompts = [
  "add a background with a zombie invasion",
  "change the background to a haunted forest",
  "replace the background with a dark and eerie graveyard",
  "set the background to a city destroyed by monsters",
  "transform the background into a haunted house full of ghosts",
  "change the background to a swamp with terrifying creatures",
  "add a background of an abandoned and cursed mansion",
  "replace the background with a giant pumpkin apocalypse",
  "set the background to a full moon over a spooky landscape",
  "change the background to a gothic castle surrounded by fog",
  "transform the background into a post-apocalyptic wasteland",
  "add a background with a creepy clown invasion",
  "change the background to a dark and foggy forest",
  "replace the background with a haunted carnival",
  "set the background to a city destroyed by zombies",
  "transform the background into a haunted asylum",
  "add a background of a dark and eerie cemetery",
  "replace the background with a foggy and mysterious swamp",
  "set the background to a post-apocalyptic city",
  "transform the background into a haunted and abandoned hospital",
];